version: "3"
services: 
    nginx:
        image: nginx:stable-alpine
        ports: 
            - "8080:80"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on: 
            - node-app-container

    node-app-container:

        depends_on:
            - mongo
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=gaurang
            - MONGO_INITDB_ROOT_PASSWORD=123
        volumes: 
            - mongo-db:/data/db

    redis:
        image: redis
    
   
        
volumes: 
    mongo-db:
        