version: "3"
services: 
    node-app-container:
        build: ./
        ports: 
            - "8080:3000"    
        depends_on:
            - mongo
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=gaurang
            - MONGO_INITDB_ROOT_PASSWORD=123
        volumes: 
            - mongo-db:/data/db

    redis:
        image: redis
        
volumes: 
    mongo-db:
        