version: "3"
services: 
    node-app-container:
        build: 
            context: ./
            args: 
                NODE_ENV: development
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONGO_USER=gaurang
            - MONGO_PASSWORD=123
            - PORT=3000
        command: npm run dev
