version: "3"
services: 
    node-app-container:
        build: ./
        ports: 
            - "8080:3000"    
        
        environment: 
            - PORT=3000
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=gaurang
            - MONGO_INITDB_ROOT_PASSWORD=123
        volumes: 
            - mongo-db:/data/db
volumes: 
    mongo-db:
        