version: "3"
services: 
    node-app-container:
        build: ./
        ports: 
            - "8080:3000"    
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - PORT=3000
        